### ISSUE TITLE
Badges are not updating

### ISSUE THREAD

**Issue by bartlannoeye** [SamVanhoutte/cotacol-site#143]
Platforms impacted:
- Website
- iOS app

Climbed 3/4 G90 climbs today (afternoon). Badge still shows 0/4 unlocked as title yet it shows 3/4 of the actual climbs unlocked.
![image](https://user-images.githubusercontent.com/5115577/157514398-bb57b512-fe0b-499f-be8c-3ff418c5ba2b.png)

Possible related actions:
I have been mainly using the site the last months and seen no issues. Logged back into the app last week to check the badges. Not sure if this might have impacted the sync job registration? Noticed that today's ride description didn't get updated yet with the cols, even after a manual resync of the activity on the site.

**Comment by SamVanhoutte** [comment]
Reason of error detected: the triggering of the badge update, after your new activity did not happen. 
For now, I have trigger the badge update for you manually , but will have to drill down to the actual reason why badge update is not automatically done.  
Thanks for the feedback already

**Comment by bartlannoeye** [comment]
Badge update triggered correctly now (for West is the Best). However Strava description still isn't updated for the ride mentioned above nor todays ride. Site shows this setting as 'enabled'.

**Comment by joaclaeys** [comment]
Seems I have the same issue. Today I completed East Flanders by conquering 3 remaining cols
"Beast Of The East" Badge still shows 26/29 - 3 missing

What to do? Thanks

**Comment by SamVanhoutte** [comment]
@bartlannoeye & @joaclaeys , looking into this - stay tuned. 
one thing is for sure: if it's on Strava, it will be on cotacol.cc, eventually ;)

**Comment by joaclaeys** [comment]
Thanks @SamVanhoutte  - strange thing in my case is: the cols have properly registered ("the list" & "my achievements"). It's only the Badge that is not picking it up it seems ...

**Comment by SamVanhoutte** [comment]
No worries, I have found the issue.  Will be deployed before noon.  It was related to an internal problem with the Grinta badges we created.

**Comment by SamVanhoutte** [comment]
@joaclaeys , look at that !
<img width="191" alt="image" src="https://user-images.githubusercontent.com/3539605/163337364-22c69cd2-5d68-4f65-85a1-e66dde8bfae2.png">

**Comment by joaclaeys** [comment]
Awesome. Thanks @SamVanhoutte .
And congrats with maintaining this great application. Keep it up!

**Comment by bartlannoeye** [comment]
Completed Grinta and unlocked 👍
