### ISSUE TITLE
Update of total points

### ISSUE THREAD

**Issue by Sat2Freak** [SamVanhoutte/cotacol-site#147]
I notice my points are no longer being updated this year.  (Have done some cotacols, but the points remain 24.800 pts.)

Thanks for looking into this

Rudy.

**Comment by SamVanhoutte** [comment]
Hello Rudy, @Sat2Freak 

I assume this was explained on the facebook group, mean while? 

If not, this has been added in the faq online, hopefully explaining why the points in your case were not increasing, by design.

```
It is important to understand that the total points you see in the different apps or site are the points 
for the unique (distinct) Cotacols you rode.
So, if your weekly training loop contains the Berendries (#792), no matter how many times you ride it, 
you'll only get the 81 points once.
```
