### ISSUE TITLE
Linking to details from the combined achievements

### ISSUE THREAD

**Issue by simonech** [SamVanhoutte/cotacol-site#61]
In the combined achievements it would be nice if the name of the segment was linked to the details of the segment, and maybe the "2 days ago" linked to the activity. And maybe the name to the "profile" page of that user.

I understand that this would need to have all those "details" pages on the site, but would make it a more "social" site.
Eventually, the home page could also be turned into a "wall" stava like... just making sure we don't turn into relieve and get banned for duplicating strava features 😄 

![image](https://user-images.githubusercontent.com/61557/109611002-ddcee280-7b2d-11eb-8a84-a8c6ba8e55a5.png)

**Comment by SamVanhoutte** [comment]
Profile page is indeed something that is planned (mostly : being able to mark your achievements page to be public), so we can do that
Having a list of activities duplicated seems to add less value, but I can indeed link the '2 days ago' to the strava activity detail page, I think

**Comment by SamVanhoutte** [comment]
Has been deployed with #88
