### ISSUE TITLE
Filter by most climbed and less climbed (or not yet)

### ISSUE THREAD

**Issue by simonech** [SamVanhoutte/cotacol-site#62]
Both the map and the list could add an additional filter: show the 50 most climbed and less climbed. And since the homepage says that only 822 / 1000 climbs were climbed, it would be nice to see which ones are not climbed

**Comment by SamVanhoutte** [comment]
yes, I was having a plan to add the "virgin" cols as a filter ;). would you have a good name for them ?

**Comment by simonech** [comment]
Maybe: unconquered?

**Comment by SamVanhoutte** [comment]
Has been deployed with #88
